version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - C:\Users\Marco\Documents\PostgreSQL\dockerPostgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_network
    volumes:
      - C:\Users\Marco\Documents\PostgreSQL\dockerPgAdmin:/var/lib/pgadmin

networks:
  postgres_network:
    driver: bridge
